root: ./

​structure:
  readme: README.md
  summary: SUMMARY.md​

redirects:
  autres-ressources/donnees-de-forte-valeur-modalites-de-rapportage: ./autres-ressources-utiles/donnees-de-forte-valeur-modalites-de-rapportage.md
